### ISSUE TITLE
Graphical Error: Fever Bar

### ISSUE THREAD

**Issue by HeyItsJinx** [Beamographic/rush#171]
Since latest update there is error with fever bar. nothing major or game just presenting weird (Cant find a way to upload screenshots so ill add another post with screenshot link)

**Comment by HeyItsJinx** [comment]
https://ibb.co/XCFgBMv

**Comment by LumpBloom7** [comment]
Seems likely that it is caused by the recent use of `LocalisableString` in `RollingCounter`, and the game is falling back to the default formatting.

I'll bump and release a hotfix build.

**Comment by LumpBloom7** [comment]
Fixed in #172 and [hotfix released](https://github.com/Beamographic/rush/releases/tag/2021.801.0)
