### ISSUE TITLE
Game not starting when rush is in osu!lazer folder

### ISSUE THREAD

**Issue by HeyItsJinx** [Beamographic/rush#173]
So my osu lazer doesnt start when rush is in my folder... the newest release which just got pushed, tested it 4 times to make sure its not me buggin out. the game just doesn't start but when i remove rush dll it works fine

**Comment by frenzibyte** [comment]
Attach logs please, should reside in `%appdata%/osu/logs`.

**Comment by LumpBloom7** [comment]
Due to the amount of time that has passed, this is likely not an issue anymore. (As seen by OP's gameplay screenshot made after this issue is created)
