### ISSUE TITLE
Needs Fixation of 20220424 Update

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Beamographic/rush#236]
![image](https://user-images.githubusercontent.com/40109698/166141350-587ec440-b438-4a1b-8993-10d2582d7c0c.png)
Trying to play it but it does not work

**Comment by LumpBloom7** [comment]
This has been fixed in #237, with a [new release](https://github.com/Beamographic/rush/releases/tag/2022.501.0) made.
