### ISSUE TITLE
Ground should use the cached information and algorithm for scrolling

### ISSUE THREAD

**Issue by frenzibyte** [Beamographic/rush#27]
Currently the ground scrolls for a duration of `groundFlow.Width / 2` per iteration. It should read from the cached scrolling info and use its scrolling algorithm.

Been working on this but for some reason the ground scrolls a bit faster than the hit object container, here's the logic I used:
```csharp
private double? startTime;

protected override void UpdateAfterChildren()
{
    base.UpdateAfterChildren();

    if (!startTime.HasValue)
        startTime = Time.Current;

    groundFlow.X = scrolling.Algorithm.PositionAt(0f, Time.Current, scrolling.TimeRange.Value, DrawWidth) % (groundFlow.Width / 2f);
}
```

**Comment by LumpBloom7** [comment]
The logic you have works. The reason why it was fast is the width of the ground is not equal to the width of the Lanes, and the algorithm assumes that the leftmost edge is offset 0. Given that the ground is about 240 units bigger, it makes it seem a bit faster.

Adding a left padding of `HIT_TARGET_OFFSET * 2` [here](https://github.com/Beamographic/rush/blob/master/osu.Game.Rulesets.Rush/UI/RushPlayfield.cs#L161) will correct the problem.

**Comment by swoolcock** [comment]
I would eventually like the ground to have barline markers.  Not sure how we do this outside of placeholder HitObjects (which is how mania does barlines).
